import './js/swiper-brands.js'
import './js/swiper-offers.js'
import './js/swiper-technical.js'
import './js/buttons.js'
import './js/main-nav.js'
import './js/icon-btns.js'
import './js/menu-navigation.js'
import './scss/style.scss'
